package se.comerit.avanza.controller;

import org.springframework.http.ResponseEntity;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import se.comerit.avanza.dto.PortfolioResponse;
import se.comerit.avanza.service.PortfolioService;

import java.util.Map;

/**
 * REST controller for portfolio data.
 * Used by React/frontend to fetch the user's full portfolio as JSON.
 * Requires a valid JWT token — userId is extracted from SecurityContext.
 */
@RestController
public class PortfolioRestController {

    private final PortfolioService portfolioService;

    public PortfolioRestController(PortfolioService portfolioService) {
        this.portfolioService = portfolioService;
    }

    /**
     * GET /api/portfolio
     * Returns the user's full portfolio (accounts, holdings, drift, alerts, etc.)
     * Data is generated by PortfolioService.buildDashboardData().
     */
    @GetMapping("api/portfolio")
    public ResponseEntity<PortfolioResponse> getPortfolio() {
        String userIdStr = (String) SecurityContextHolder.getContext()
                .getAuthentication()
                .getPrincipal();

        Long uid = Long.valueOf(userIdStr);
        PortfolioResponse portfolio = portfolioService.getPortfolioResponse(uid);

        return ResponseEntity.ok(portfolio);
    }
}

