package se.comerit.avanza.controller;

import org.springframework.http.ResponseEntity;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import se.comerit.avanza.service.PortfolioService;

import java.util.Map;

/**
 * REST controller for portfolio data.
 * Used by React/frontend to fetch the user's full portfolio as JSON.
 * Requires a valid JWT token — userId is extracted from SecurityContext.
 */
@RestController
public class PortfolioRestController {

    private final PortfolioService portfolioService;

    public PortfolioRestController(PortfolioService portfolioService) {
        this.portfolioService = portfolioService;
    }

    /**
     * GET /api/portfolio
     * Returns the user's full portfolio (accounts, holdings, drift, alerts, etc.)
     * Data is generated by PortfolioService.buildDashboardData().
     */
    @GetMapping("/api/portfolio")
    public ResponseEntity<Map<String, Object>> getPortfolio() {

        // Extract userId from JWT stored in SecurityContext (set by JwtFilter)
        String userId = (String) SecurityContextHolder.getContext()
                .getAuthentication()
                .getPrincipal();

        Long uid = Long.valueOf(userId);

        // Build full portfolio dataset for the authenticated user
        Map<String, Object> data = portfolioService.buildDashboardData(uid);

        // Return JSON response
        return ResponseEntity.ok(data);
    }
}
